export default ~(() => {
  // [{ type: "🍇", commit: "👍🏿" },{ type: "🥕", commit: "😭" }]
  
  const data = [
    {
        "id":79819,
        "rankScore":"1.0",
        "prob":null,
        "stdNo":"KGJB 5063-2001",
        "nameCn":"航空航天用超高强度钢钢棒规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9510  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9510",
        "searchHType":"GJB",
        "editor":"抚顺特钢(集团)有限责任公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2001-11-23 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79075,
        "rankScore":0.969,
        "prob":null,
        "stdNo":"GJB 8918-2017",
        "nameCn":"航空无线电导航装备电磁频谱参数限值和测量方法",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"B1271  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-航电系统",
        "gjbType":null,
        "searchGjbType":"B1271",
        "searchHType":"GJB",
        "editor":"军委联合作战指挥中心频谱管控大队;空军工程大学;空军电磁频谱管理中心",
        "sysName":null,
        "sysCode":"1.1.2",
        "sysId":null,
        "pubDate":"2017-05-18 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79115,
        "rankScore":0.939,
        "prob":null,
        "stdNo":"GJB 107B-2013",
        "nameCn":"航空轮胎设计要求",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"B1111  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"B1111",
        "searchHType":"GJB",
        "editor":"中橡集团曙光橡胶工业研究设计院",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"2013-07-10 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79365,
        "rankScore":0.939,
        "prob":null,
        "stdNo":"GJB 3366-1998",
        "nameCn":"航空涡轮发动机包容性要求",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A2840  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-试验标准-飞行试验",
        "gjbType":null,
        "searchGjbType":"A2840",
        "searchHType":"GJB",
        "editor":"试飞院",
        "sysName":null,
        "sysCode":"1.3.2",
        "sysId":null,
        "pubDate":"1998-07-27 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79552,
        "rankScore":0.908,
        "prob":null,
        "stdNo":"GJB 500A-1997",
        "nameCn":"飞机玻璃术语",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9340  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-飞行器-结构",
        "gjbType":null,
        "searchGjbType":"A9340",
        "searchHType":"GJB",
        "editor":"建材科学院玻璃所",
        "sysName":null,
        "sysCode":"1.1.1.4",
        "sysId":null,
        "pubDate":"1997-11-05 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79751,
        "rankScore":0.878,
        "prob":null,
        "stdNo":"KGJB 2053A-2008",
        "nameCn":"航空航天用铝合金结构板规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B6210 室内和室外电气照明设备",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"B6210",
        "searchHType":"GJB",
        "editor":"西南铝业(集团)有限责任公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2008-03-17 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78035,
        "rankScore":0.847,
        "prob":null,
        "stdNo":"KGJB 6470-2008",
        "nameCn":"航空航天用铝合金蒙皮板规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B6210 室内和室外电气照明设备",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"B6210",
        "searchHType":"GJB",
        "editor":"",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2008-03-17 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79399,
        "rankScore":0.806,
        "prob":null,
        "stdNo":"GJB 4598-1992(GJBz 20096-1992)",
        "nameCn":"航空附件履历本",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"11  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-服务标准-技术资料",
        "gjbType":null,
        "searchGjbType":"11",
        "searchHType":"GJB",
        "editor":"",
        "sysName":null,
        "sysCode":"1.4.7",
        "sysId":null,
        "pubDate":"1992-09-28 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78056,
        "rankScore":0.796,
        "prob":null,
        "stdNo":"GJB 684A-1998",
        "nameCn":"军用航空轮胎系列",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A2620  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"A2620",
        "searchHType":"GJB",
        "editor":"曙光橡胶工业所",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"1998-03-16 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78861,
        "rankScore":0.755,
        "prob":null,
        "stdNo":"GJB 997A-1996",
        "nameCn":"航空充气轮胎内胎规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A2620  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"A2620",
        "searchHType":"GJB",
        "editor":"曙光橡胶研究所",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"1996-10-03 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":77896,
        "rankScore":0.745,
        "prob":null,
        "stdNo":"KGJB 5473-2005",
        "nameCn":"航空炸弹电缆规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B1120 核深水炸弹",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-武器系统",
        "gjbType":null,
        "searchGjbType":"B1120",
        "searchHType":"GJB",
        "editor":"",
        "sysName":null,
        "sysCode":"1.1.5",
        "sysId":null,
        "pubDate":"2005-12-12 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78596,
        "rankScore":0.724,
        "prob":null,
        "stdNo":"GJB 2151-1994",
        "nameCn":"航空用合金结构钢冷轧钢板规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9515  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9515",
        "searchHType":"GJB",
        "editor":"重庆特钢公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1994-12-13 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79012,
        "rankScore":0.724,
        "prob":null,
        "stdNo":"GJB 3209-1998",
        "nameCn":"直升机术语",
        "className":null,
        "classNo":null,
        "classType":"A",
        "classAllName":"A1520 武器系统标准",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-飞行器",
        "gjbType":null,
        "searchGjbType":"A1520",
        "searchHType":"GJB",
        "editor":"航空总公司602所",
        "sysName":null,
        "sysCode":"1.1.1",
        "sysId":null,
        "pubDate":"1998-03-16 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79538,
        "rankScore":0.694,
        "prob":null,
        "stdNo":"GJB 4882-2003",
        "nameCn":"导航术语",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A5800  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-航电系统",
        "gjbType":null,
        "searchGjbType":"A5800",
        "searchHType":"GJB",
        "editor":"信息产业部电子四所",
        "sysName":null,
        "sysCode":"1.1.2",
        "sysId":null,
        "pubDate":"2003-07-21 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79755,
        "rankScore":0.694,
        "prob":null,
        "stdNo":"KGJB 2150A-2005",
        "nameCn":"航空用合金结构钢热轧钢板规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B6210 室内和室外电气照明设备",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"B6210",
        "searchHType":"GJB",
        "editor":"重庆特钢集团有限公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2005-12-12 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79483,
        "rankScore":0.663,
        "prob":null,
        "stdNo":"GJB 2150A-2018",
        "nameCn":"航空用合金结构钢热轧钢板规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B6210 室内和室外电气照明设备",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"B6210",
        "searchHType":"GJB",
        "editor":"鞍钢股份有限公司;沈阳飞机工业(集团)有限公司;北京航空材料研究院;抚顺特殊钢股份有限公司;冶金工业信息标准研究院",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2018-03-27 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79779,
        "rankScore":0.663,
        "prob":null,
        "stdNo":"KGJB 3019A-2008",
        "nameCn":"航空防弹钢板规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B6210 室内和室外电气照明设备",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"B6210",
        "searchHType":"GJB",
        "editor":"重庆钢铁股份有限公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2008-03-17 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":77910,
        "rankScore":0.633,
        "prob":null,
        "stdNo":"GJB 1263-1991",
        "nameCn":"航空涡轮发动机用合成润滑油",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9150  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9150",
        "searchHType":"GJB",
        "editor":"石化总公司一坪化工厂",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1991-10-18 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78772,
        "rankScore":0.633,
        "prob":null,
        "stdNo":"GJB 2643A-2011",
        "nameCn":"飞机空调车通用规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"B1170  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-服务标准-保障设备",
        "gjbType":null,
        "searchGjbType":"B1170",
        "searchHType":"GJB",
        "editor":"空军驻沈阳地区军代室;沈阳航空工业学院",
        "sysName":null,
        "sysCode":"1.4.6",
        "sysId":null,
        "pubDate":"2011-01-20 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78324,
        "rankScore":0.612,
        "prob":null,
        "stdNo":"GJB 1688A-2012",
        "nameCn":"航空磁罗盘通用规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"B1119  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-航电系统",
        "gjbType":null,
        "searchGjbType":"B1119",
        "searchHType":"GJB",
        "editor":"解放军驻212厂军事代表室;国营第212厂",
        "sysName":null,
        "sysCode":"1.1.2",
        "sysId":null,
        "pubDate":"2012-12-27 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":77889,
        "rankScore":0.602,
        "prob":null,
        "stdNo":"GJB 1219-1991",
        "nameCn":"航空活塞式发动机润滑油",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9150  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9150",
        "searchHType":"GJB",
        "editor":"空军油料所",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1991-10-18 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":77928,
        "rankScore":0.541,
        "prob":null,
        "stdNo":"GJB 1284-1991",
        "nameCn":"航空燃气涡轮发动机的封存包装",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A2840  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-服务标准-包装、装卸、贮存和运输",
        "gjbType":null,
        "searchGjbType":"A2840",
        "searchHType":"GJB",
        "editor":"解放军驻420厂军代室",
        "sysName":null,
        "sysCode":"1.4.5",
        "sysId":null,
        "pubDate":"1991-12-23 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78960,
        "rankScore":0.52,
        "prob":null,
        "stdNo":"GJB 309-1987",
        "nameCn":"航空汽油飞行试验规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9130  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-试验标准-飞行试验",
        "gjbType":null,
        "searchGjbType":"A9130",
        "searchHType":"GJB",
        "editor":"空军油料所",
        "sysName":null,
        "sysCode":"1.3.2",
        "sysId":null,
        "pubDate":"1987-05-17 23:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78298,
        "rankScore":0.51,
        "prob":null,
        "stdNo":"GJB 1619-1993",
        "nameCn":"低温航空润滑脂规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9150  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9150",
        "searchHType":"GJB",
        "editor":"空军油料所",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1993-03-08 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":77813,
        "rankScore":0.49,
        "prob":null,
        "stdNo":"GJB 1170-1991",
        "nameCn":"低挥发航空仪表油",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9150  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9150",
        "searchHType":"GJB",
        "editor":"石化一坪化工厂",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1991-10-18 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78288,
        "rankScore":0.49,
        "prob":null,
        "stdNo":"GJB 1589-1993",
        "nameCn":"航空用氧气橡胶软管规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A4720  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A4720",
        "searchHType":"GJB",
        "editor":"沈阳橡胶工业制品所",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1993-03-08 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78030,
        "rankScore":0.48,
        "prob":null,
        "stdNo":"GJB 1360-1992",
        "nameCn":"航空发动机包装箱设计",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A8115  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-服务标准-包装、装卸、贮存和运输",
        "gjbType":null,
        "searchGjbType":"A8115",
        "searchHType":"GJB",
        "editor":"解放军驻420厂军代室",
        "sysName":null,
        "sysCode":"1.4.5",
        "sysId":null,
        "pubDate":"1992-07-18 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78408,
        "rankScore":0.48,
        "prob":null,
        "stdNo":"GJB 181A-2003",
        "nameCn":"飞机供电特性",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A5900  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"A5900",
        "searchHType":"GJB",
        "editor":"中国航空综合技术研究所",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"2003-07-21 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78410,
        "rankScore":0.449,
        "prob":null,
        "stdNo":"GJB 181B-2012",
        "nameCn":"飞机供电特性",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B1115 核弹头和核战斗部",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"B1115",
        "searchHType":"GJB",
        "editor":"成都飞机设计研究所;中国航空综合技术研究所;空军装备研究院总体所;西北工业大学;第一飞机设计研究院;沈阳飞机设计研究所",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"2012-12-27 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78522,
        "rankScore":0.449,
        "prob":null,
        "stdNo":"GJB 2053-1994",
        "nameCn":"航空航天用铝合金薄板规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9535  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9535",
        "searchHType":"GJB",
        "editor":"西南铝加工厂",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1994-09-12 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78782,
        "rankScore":0.418,
        "prob":null,
        "stdNo":"GJB 2662A-2015",
        "nameCn":"航空航天用铝合金厚板规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B6210 室内和室外电气照明设备",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"B6210",
        "searchHType":"GJB",
        "editor":"东北轻合金有限责任公司;有色金属工业标准计量质量标准所;北京航空材料研究院;沈阳飞机工业（集团）有限公司;中国运载火箭技术研究院;航天708所;西南铝业（集团）有限责任公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2015-12-19 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79482,
        "rankScore":0.418,
        "prob":null,
        "stdNo":"GJB 4558-2004",
        "nameCn":"飞机称重要求",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A1510  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-制造标准-飞机功能试验与检测",
        "gjbType":null,
        "searchGjbType":"A1510",
        "searchHType":"GJB",
        "editor":"解放军驻162厂军代室",
        "sysName":null,
        "sysCode":"1.2.9",
        "sysId":null,
        "pubDate":"2004-03-10 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78694,
        "rankScore":0.388,
        "prob":null,
        "stdNo":"GJB 241A-2010",
        "nameCn":"航空涡轮喷气和涡轮风扇发动机通用规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"B1117  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-动力系统",
        "gjbType":null,
        "searchGjbType":"B1117",
        "searchHType":"GJB",
        "editor":"空军装备研究院装备总体论证研究所;航空工业第一集团公司沈阳发动机设计研究所",
        "sysName":null,
        "sysCode":"1.1.6",
        "sysId":null,
        "pubDate":"2010-09-16 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78703,
        "rankScore":0.388,
        "prob":null,
        "stdNo":"GJB 867-1990",
        "nameCn":"航空加压供氧生理要求",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A0121  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"A0121",
        "searchHType":"GJB",
        "editor":"空四所",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"1990-10-31 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79687,
        "rankScore":0.388,
        "prob":null,
        "stdNo":"GJBz 20355-1996",
        "nameCn":"直升机噪声限值",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"11  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-飞行器",
        "gjbType":null,
        "searchGjbType":"11",
        "searchHType":"GJB",
        "editor":"中国人民解放军空军第一研究所",
        "sysName":null,
        "sysCode":"1.1.1",
        "sysId":null,
        "pubDate":"1996-11-25 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78688,
        "rankScore":0.367,
        "prob":null,
        "stdNo":"GJB 2414-1995",
        "nameCn":"航空救生电台通用规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A5820  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-航电系统",
        "gjbType":null,
        "searchGjbType":"A5820",
        "searchHType":"GJB",
        "editor":"空军驻769厂军代室",
        "sysName":null,
        "sysCode":"1.1.2",
        "sysId":null,
        "pubDate":"1995-05-31 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78027,
        "rankScore":0.357,
        "prob":null,
        "stdNo":"GJB 135A-1998",
        "nameCn":"合成航空润滑油规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9150  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9150",
        "searchHType":"GJB",
        "editor":"石化一坪高级润滑油公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1998-07-27 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78290,
        "rankScore":0.357,
        "prob":null,
        "stdNo":"GJB 1590-1993",
        "nameCn":"H61-1航空用环氧有机硅耐热漆规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A8010  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A8010",
        "searchHType":"GJB",
        "editor":"天津油漆总厂",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1993-03-08 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78863,
        "rankScore":0.357,
        "prob":null,
        "stdNo":"GJB_Z 100-1997",
        "nameCn":"飞机安全电接地",
        "className":null,
        "classNo":null,
        "classType":"A",
        "classAllName":"A1500 综合标准",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":" ",
        "gjbType":null,
        "searchGjbType":"A1500",
        "searchHType":"GJB",
        "editor":"航空总公司301所",
        "sysName":null,
        "sysCode":"",
        "sysId":null,
        "pubDate":"1997-11-05 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79333,
        "rankScore":0.357,
        "prob":null,
        "stdNo":"GJB 982A-2012",
        "nameCn":"航空刹车胎规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"B1111  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"B1111",
        "searchHType":"GJB",
        "editor":"解放军驻沈阳第四橡胶厂军事代表室",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"2012-07-24 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78446,
        "rankScore":0.337,
        "prob":null,
        "stdNo":"GJB 1882-1994",
        "nameCn":"航空炸弹通用规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A1325  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-武器系统",
        "gjbType":null,
        "searchGjbType":"A1325",
        "searchHType":"GJB",
        "editor":"国营624厂",
        "sysName":null,
        "sysCode":"1.1.5",
        "sysId":null,
        "pubDate":"1994-04-28 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":77764,
        "rankScore":0.327,
        "prob":null,
        "stdNo":"KGJB 5154-2002",
        "nameCn":"航空航天用镁合金锻件规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9570  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9570",
        "searchHType":"GJB",
        "editor":"",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2002-11-18 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78021,
        "rankScore":0.327,
        "prob":null,
        "stdNo":"GJB 1357-1992",
        "nameCn":"飞机内的噪声级",
        "className":null,
        "classNo":null,
        "classType":"A",
        "classAllName":"A1500 综合标准",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-飞行器",
        "gjbType":null,
        "searchGjbType":"A1500",
        "searchHType":"GJB",
        "editor":"空四所",
        "sysName":null,
        "sysCode":"1.1.1",
        "sysId":null,
        "pubDate":"1992-07-18 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78046,
        "rankScore":0.327,
        "prob":null,
        "stdNo":"KGJB 750A-2001",
        "nameCn":"航空用钢丝编织软管规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A4720  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A4720",
        "searchHType":"GJB",
        "editor":"沈阳橡胶研究设计院",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2001-11-23 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":78672,
        "rankScore":0.296,
        "prob":null,
        "stdNo":"GJB 2351-1995",
        "nameCn":"航空航天用铝合金锻件规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9570  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9570",
        "searchHType":"GJB",
        "editor":"航空总公司621所",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"1995-05-31 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79446,
        "rankScore":0.245,
        "prob":null,
        "stdNo":"GJB 4430-2002",
        "nameCn":"航空炸弹靶场试验规程",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A0120  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-试验标准-飞行试验",
        "gjbType":null,
        "searchGjbType":"A0120",
        "searchHType":"GJB",
        "editor":"解放军驻624厂军代室",
        "sysName":null,
        "sysCode":"1.3.2",
        "sysId":null,
        "pubDate":"2003-02-08 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79754,
        "rankScore":0.235,
        "prob":null,
        "stdNo":"GJB 5583-2006",
        "nameCn":"航弹伞通用规范",
        "className":null,
        "classNo":null,
        "classType":"B",
        "classAllName":"B1120 核深水炸弹",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-武器系统",
        "gjbType":null,
        "searchGjbType":"B1120",
        "searchHType":"GJB",
        "editor":"空军驻湖北第二军代室",
        "sysName":null,
        "sysCode":"1.1.5",
        "sysId":null,
        "pubDate":"2006-05-17 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79721,
        "rankScore":0.184,
        "prob":null,
        "stdNo":"KGJB 1255A-2001",
        "nameCn":"航空供氧面罩规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A1660  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-设计标准-机电系统",
        "gjbType":null,
        "searchGjbType":"A1660",
        "searchHType":"GJB",
        "editor":"上海胶带股份有限公司",
        "sysName":null,
        "sysCode":"1.1.3",
        "sysId":null,
        "pubDate":"2001-04-04 00:00:00",
        "htype":"国家军用标准(GJB)"
    },
    {
        "id":79813,
        "rankScore":0.122,
        "prob":null,
        "stdNo":"KGJB 5040-2001",
        "nameCn":"航空用钢锻件规范",
        "className":null,
        "classNo":null,
        "classType":"null",
        "classAllName":"A9570  ",
        "pdfExist":"0",
        "secretLevel":"内部",
        "stdStatus":"有效",
        "parentNames":"集团公司执行标准体系架构-产品实现标准-通用标准-航空材料",
        "gjbType":null,
        "searchGjbType":"A9570",
        "searchHType":"GJB",
        "editor":"陕西飞机工业(集团)有限公司",
        "sysName":null,
        "sysCode":"1.5.8",
        "sysId":null,
        "pubDate":"2001-11-23 00:00:00",
        "htype":"国家军用标准(GJB)"
    }
]

  const multiply = [{ searchHType: "G" }, { sysCode: undefined }];

  const filterFunc = (source: any[], filterData: any[]) => {
    // 将数据打平成一个对象
    const format = source.reduce((p: any, n: any) => ({ ...n, ...p }), {});
    const keys = Object.keys(format);
    const isUnd = (x: unknown) => x === undefined
    const isStr = (x: unknown) => typeof x === 'string'
    const eq = (l: string, r: string) => isStr(l) ? l.includes(r) : l === r
    return filterData.filter((di: any) =>
      keys.every((ki: any) => isUnd(di[ki]) || isUnd(format[ki]) || eq(di[ki], format[ki]))
    );
  };

  const result = filterFunc(multiply, data);
  console.log(result);
})();
